
# -----------------------------------------------
# Makfile for CYBERDEF101
# Build all output files :
#       needs :
#		imagemagick
#		ghoscript
#		TexLive
# -----------------------------------------------
MAKEFLAGS += --no-builtin-rules
#MAKEFLAGS += --no-builtin-variables
.SUFFIXES:
SUFFIXES:= 
%.tex:
%.acr:



clean:
	latexmk -c
	rm -f *.xml
	rm -f *.bbl
	rm -f *.snm
	rm -f *.ptc 
	rm -f *.nav



	
