tex4ht=new Array() ; //2023-01-26 18:01:00
tex4ht.fn1x2="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn1x2\">1.  </a></span><span class=\"ecrm-0900\">cf.  Certification et Qualification de produits de s</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">curit</span><span class=\"ecrm-0900\"></span> <span class=\"ecrm-0900\">et Crit</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">res communs</span> </div>";
tex4ht.fn2x2="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn2x2\">2.  </a></span><span class=\"ecrm-0900\">Historiquement dautres termes sont utilis</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">s comme </span><a href=\"#glo:aSSI\"><span class=\"ecrm-0900\">S</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">curit</span><span class=\"ecrm-0900\"></span> <span class=\"ecrm-0900\">des Syst</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">mes</span> <span class=\"ecrm-0900\">dinformation (SSI)</span></a> <span class=\"ecrm-0900\">ou S</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">curit</span><span class=\"ecrm-0900\"></span> <span class=\"ecrm-0900\">Informatique</span></div>";
tex4ht.fn3x2="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn3x2\">3.  </a></span><a href=\"#glo:aOIV\"><span class=\"ecrm-0900\">Op</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">rateur dInfrastructures Vitales (OIV)</span></a> <span class=\"ecrm-0900\">et </span><a href=\"#glo:aOSE\"><span class=\"ecrm-0900\">Op</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">rateur de Services Essentiels (OSE)</span></a> </div>";
tex4ht.fn4x2="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn4x2\">4.  </a></span><span class=\"ecrm-0900\">Lanceurs dalertes, comportements d</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">viants des utilisateurs l</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">gitimes</span></div>";
tex4ht.fn1x3="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn1x3\">1.  </a></span><span class=\"ecrm-0900\">IAM : Identity et Access Management</span></div>";
tex4ht.fn1x6="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn1x6\">1.  </a></span><span class=\"ecrm-0900\">t</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">l</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">phonie mobile (SIM) et carte bancaire.</span></div>";
tex4ht.fn2x6="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn2x6\">2.  </a></span><span class=\"ecrm-0900\">ARCSI : Association des r</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">servistes du chiffre et de la s</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">curit</span><span class=\"ecrm-0900\"></span> <span class=\"ecrm-0900\">de linformation -</span> <span class=\"ecrm-0900\">www.arcsi.fr</span></div>";
tex4ht.fn3x6="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn3x6\">3.  </a></span><span class=\"ecrm-0900\">National institute of standards and technology.</span></div>";
tex4ht.fn4x6="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn4x6\">4.  </a></span><span class=\"ecrm-0900\">Anssi :  Agence nationale pour la s</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">curit</span><span class=\"ecrm-0900\"></span> <span class=\"ecrm-0900\">des syt</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">me dinformation, services du</span> <span class=\"ecrm-0900\">Premier ministre.</span></div>";
tex4ht.fn5x6="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn5x6\">5.  </a></span><span class=\"ecrm-0900\">Annexe B1 et B2 du RGS V2 (Anssi :  r</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">f</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">rentiel g</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">n</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">ral de s</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">curit</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">) :</span> <span class=\"ecrm-0900\">M</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">canismes cryptographiques et gestion des clefs.</span></div>";
tex4ht.fn6x6="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn6x6\">6.  </a></span><span class=\"ecrm-0900\">1978, apparition de lalgorithme </span><span class=\"ecrm-0900\"></span> <span class=\"ecrm-0900\">clef publique de Rivest, Shamir et Adelman</span> <span class=\"ecrm-0900\">(RSA).</span></div>";
tex4ht.fn7x6="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn7x6\">7.  </a></span><span class=\"ecrm-0900\">Un mot de passe de qualit</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\"> cryptographique  devrait </span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">tre dau moins 20 caract</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">res</span> <span class=\"ecrm-0900\">dans un alphabet de 90 symboles.</span></div>";
tex4ht.fn1x8="<div class=\"js\"><span class=\"footnote-mark\"><a id=\"fn1x8\">1.  </a></span><span class=\"ecrm-0900\">syst</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">mes dinformation de lentreprise, services dans les cloud, r</span><span class=\"ecrm-0900\"></span><span class=\"ecrm-0900\">seaux sociaux...</span></div>";
 ol_hauto = 1; 


